plugin.plugin_configuration.geolocation.map_feature.drawing:
  type: geolocation.map_feature_settings
  label: 'Common map draw settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        polyline:
          type: string
          label: 'Draw polyline'
        strokeColor:
          type: string
          label: 'strokeColor'
        strokeOpacity:
          type: string
          label: 'strokeOpacity'
        strokeWeight:
          type: string
          label: 'strokeWeight'
        geodesic:
          type: string
          label: 'Geodesic'
        polygon:
          type: string
          label: 'Draw polygon'
        fillColor:
          type: string
          label: 'fillColor'
        fillOpacity:
          type: string
          label: 'fillOpacity'

plugin.plugin_configuration.geolocation.map_feature.marker_clusterer:
  type: geolocation.map_feature_settings
  label: 'Marker clusterer'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        image_path:
          type: string
          label: 'Image path'
        styles:
          type: string
          label: 'Styles'
        max_zoom:
          type: string
          label: 'Max Zoom'

plugin.plugin_configuration.geolocation.map_feature.context_popup:
  type: geolocation.map_feature_settings
  label: 'Context Popup'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        content:
          type: text_format
          label: 'Content'

plugin.plugin_configuration.geolocation.map_feature.map_type_style:
  type: geolocation.map_feature_settings
  label: 'MapType Style'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        style:
          type: string
          label: 'Style'

plugin.plugin_configuration.geolocation.map_feature.marker_infowindow:
  type: geolocation.map_feature_settings
  label: 'Marker InfoWindow'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        info_window_solitary:
          type: integer
          label: 'Show only one window at a time'
        disable_auto_pan:
          type: integer
          label: 'Do not move map on window open'
        info_auto_display:
          type: integer
          label: 'Show info window on map start'

plugin.plugin_configuration.geolocation.map_feature.marker_icon:
  type: geolocation.map_feature_settings
  label: 'Marker Icon Adjustments'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        marker_icon_path:
          type: string
          label: 'Marker Icon Path'
        anchor:
          type: mapping
          label: 'Anchor'
          mapping:
            x:
              type: integer
              label: 'X'
            y:
              type: integer
              label: 'Y'
        origin:
          type: mapping
          label: 'Origin'
          mapping:
            x:
              type: integer
              label: 'X'
            y:
              type: integer
              label: 'Y'
        label_origin:
          type: mapping
          label: 'Label Origin'
          mapping:
            x:
              type: integer
              label: 'X'
            y:
              type: integer
              label: 'Y'
        size:
          type: mapping
          label: 'Size'
          mapping:
            width:
              type: integer
              label: 'Width'
            height:
              type: integer
              label: 'Height'
        scaled_size:
          type: mapping
          label: 'Scaled Size'
          mapping:
            width:
              type: integer
              label: 'Width'
            height:
              type: integer
              label: 'Height'

plugin.plugin_configuration.geolocation.map_feature.marker_infobubble:
  type: geolocation.map_feature_settings
  label: 'Marker InfoBubble'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        close_other:
          type: integer
          label: 'Close other'
        close_button:
          type: integer
          label: 'Close Button'
        close_button_src:
          type: string
          label: 'URL to button'
        shadow_style:
          type: integer
          label: 'Shadow style'
        padding:
          type: integer
          label: 'Padding'
        border_radius:
          type: integer
          label: 'Border Radius'
        border_width:
          type: integer
          label: 'Border Width'
        border_color:
          type: string
          label: 'Border color'
        background_color:
          type: string
          label: 'Background color'
        min_width:
          type: integer
          label: 'Min Width'
        max_width:
          type: integer
          label: 'Max Width'
        min_height:
          type: integer
          label: 'Min Height'
        max_height:
          type: integer
          label: 'Max Height'

geolocation_google_maps.map_control_feature_settings:
  type: geolocation.map_feature_settings
  label: 'Control Map Feature'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        position:
          type: string
          label: 'Position'

plugin.plugin_configuration.geolocation.map_feature.control_recenter:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Recenter'

plugin.plugin_configuration.geolocation.map_feature.control_locate:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Locate'

plugin.plugin_configuration.geolocation.map_feature.control_geocoder:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Geocoder'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        geocoder:
          type: string
          label: 'Geocoder'
        settings:
          type: geolocation.geocoder.google_geocoding_api

plugin.plugin_configuration.geolocation.map_feature.control_zoom:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Zoom'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        behavior:
          type: string
          label: 'Behavior'
        style:
          type: string
          label: 'Style'

plugin.plugin_configuration.geolocation.map_feature.control_streetview:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control Streetview'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        behavior:
          type: string
          label: 'Behavior'

plugin.plugin_configuration.geolocation.map_feature.control_maptype:
  type: geolocation_google_maps.map_control_feature_settings
  label: 'Control MapType'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        behavior:
          type: string
          label: 'Behavior'
        style:
          type: string
          label: 'Style'