geolocation_google_maps.settings:
  type: config_object
  label: 'Geolocation settings'
  mapping:
    google_map_api_key:
      type: string
      label: 'Google Maps API Key'
    google_map_api_server_key:
      type: string
      label: 'Google Maps API Key'
    use_current_language:
      type: integer
      label: 'Use current language'
    china_mode:
      type: integer
      label: 'China mode'
    google_map_custom_url_parameters:
      type: mapping
      label: 'Additional Google Maps API parameters'
      mapping:
        region:
          type: string
          label: 'Region'
        language:
          type: string
          label: 'languae'
        v:
          type: string
          label: 'Version'
        client:
          type: string
          label: 'Client ID'
        libraries:
          type: sequence
          label: 'Libraries'
          sequence:
            type: string
            label: 'Library name'

views.style.maps_common:
  type: geolocation_views_style
  label: 'Geolocation CommonMap'
  mapping:
    google_map_settings:
      type: geolocation.map_provider.google_maps
      label: 'Google Map settings'

geolocation.geocoder.google_geocoding_api:
  type: geolocation_geocoder
  label: 'Google Geocoding API'
  mapping:
    component_restrictions:
      type: mapping
      label: 'Components'
      mapping:
        route:
          type: string
          label: 'Route'
        country:
          type: string
          label: 'Country'
        administrative_area:
          type: string
          label: 'Administrative Area'
        locality:
          type: string
          label: 'Locality'
        postal_code:
          type: string
          label: 'Postal Code'

geolocation.map_provider.google_maps:
  type: geolocation_map_provider
  label: 'Google Map settings'
  mapping:
    type:
      type: string
      label: 'Google map type'
    zoom:
      type: string
      label: 'Zoom level'
    minZoom:
      type: string
      label: 'Min Zoom'
    maxZoom:
      type: string
      label: 'Max Zoom'
    rotateControl:
      type: boolean
      label: 'The state of the rotate control'
    scrollwheel:
      type: boolean
      label: 'Scrool wheel'
    disableDoubleClickZoom:
      type: string
      label: 'Disable double click zoom'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'
    info_auto_display:
      type: boolean
      label: 'Display info'
    disableAutoPan:
      type: boolean
      label: 'Disable automatic panning for info window'
    style:
      type: string
      label: 'JSON encoded style'
    preferScrollingToZooming:
      type: boolean
      label: 'Require user to click map before zooming'
    gestureHandling:
      type: string
      label: 'Smart scrolling'
