openy_popups.settings:
  type: config_object
  label: 'Open Y Popups config'
  mapping:
    img:
      type: text
      label: 'Image'
    description:
      type: text
      label: 'Description'
    location: 
      type: text
      label: 'Default Location'
