openy_upgrade_tool.settings:
  type: config_object
  label: 'Open Y Upgrade Tool Settings'
  mapping:
    force_mode:
      type: boolean
      label: 'Force mode'
action.configuration.apply_active_version:
  type: action_configuration_default
  label: 'Apply current active version'

action.configuration.apply_openy_version:
  type: action_configuration_default
  label: 'Apply Open Y version'
