views.style.geolocation_leaflet:
  type: geolocation_views_style
  label: 'Leaflet common map'
  mapping:
    leaflet_settings:
      type: geolocation.map_provider.leaflet
      label: 'Leaflet settings'

geolocation.map_provider.leaflet:
  type: geolocation_map_provider
  label: 'Leaflet settings'
  mapping:
    zoom:
      type: string
      label: 'Zoom level'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'
