# Check https://circleci.com/docs/2.0/language-php/ for more details.
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here.
      # See https://circleci.com/docs/2.0/circleci-images/ for more details.
      - image: circleci/php:7.1.8-browsers

    working_directory: ~/openy

    steps:
      - checkout

      # Download and cache dependencies.
      - restore_cache:
          keys:
          - composer-v1-dependencies-{{ checksum "composer.json" }}
          # Fallback to using the latest cache if no exact match is found.
          - composer-v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
