advanced_help_block.advanced_help_block.*:
  type: config_entity
  label: 'Advanced Help Block config'
  mapping:
    id:
      type: string
      label: 'ID'
    changed:
      type: timestamp
      label: 'Changed'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    video:
      type: string
      label: 'Video'
    pages:
      type: string
      label: 'Pages'
    visibility:
      type: string
      label: 'Visibility rules'
